version: "3.8"

services:

  backend:
    build: ./backend
    ports:
      - 8888:80
    environment:
      DB_URL: mongodb://database

  frontend:
    build: ./frontend
    ports:
      - 3000:3000

  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - db_store:/data/db

volumes:
  db_store: 