version: "3.8"

services:

  backend:
    build: ./backend
    ports:
      - 8888:80
    environment:
      MONGODB_PORT: 27017
      MONGO_HOST_URL: mongodb://database
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: admin
    depends_on:
      - database

  frontend:
    build: ./frontend
    ports:
      - 3000:3000

  database:
    image: mongo:4.0-xenial
    ports:
      - 27017:27017
    volumes:
      - db_store:/data/db 
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: adminpassword
      MONGO_INITDB_DATABASE: admin

volumes:
  db_store: 
