# Resource Set
RESOURCES_SET = ["HW Set 1", "HW Set 2", "HW Set 3"]

# HTTP Status Code
CONTINUE = ({"msg": "Continue"}, 100)
SWITCHING_PROTOCOLS = ({"msg": "Switching Protocols"}, 101)
PROCESSING = ({"msg": "Processing"}, 102)
CHECKPOINT = ({"msg": "Checkpoint"}, 103)

OK = ({"msg": "OK"}, 200)
CREATED = ({"msg": "Created"}, 201)
ACCEPTED = ({"msg": "Accepted"}, 202)
NON_AUTHORITATIVE_INFORMATION = ({"msg": "Non-Authoritative Information"}, 203)
NO_CONTENT = ({"msg": "No Content"}, 204)
RESET_CONTENT = ({"msg": "Reset Content"}, 205)
PARTIAL_CONTENT = ({"msg": "Partial Content"}, 206)
MULTI_STATUS = ({"msg": "Multi-Status"}, 207)
ALREADY_REPORTED = ({"msg": "Already Reported"}, 208)
IM_USED = ({"msg": "IM Used"}, 226)

MULTIPLE_CHOICES = ({"msg": "Multiple Choices"}, 300)
MOVED_PERMANENTLY = ({"msg": "Moved Permanently"}, 301)
FOUND = ({"msg": "Found"}, 302)
MOVED_TEMPORARILY = ({"msg": "Moved Temporarily"}, 302)
SEE_OTHER = ({"msg": "See Other"}, 303)
NOT_MODIFIED = ({"msg": "Not Modified"}, 304)
USE_PROXY = ({"msg": "Use Proxy"}, 305)
TEMPORARY_REDIRECT = ({"msg": "Temporary Redirect"}, 307)
PERMANENT_REDIRECT = ({"msg": "Permanent Redirect"}, 308)

BAD_REQUEST = ({"msg": "Bad Request"}, 400)
UNAUTHORIZED = ({"msg": "Unauthorized"}, 401)
PAYMENT_REQUIRED = ({"msg": "Payment Required"}, 402)
FORBIDDEN = ({"msg": "Forbidden"}, 403)
NOT_FOUND = ({"msg": "Not Found"}, 404)
METHOD_NOT_ALLOWED = ({"msg": "Method Not Allowed"}, 405)
NOT_ACCEPTABLE = ({"msg": "Not Acceptable"}, 406)
PROXY_AUTHENTICATION_REQUIRED = ({"msg": "Proxy Authentication Required"}, 407)
REQUEST_TIMEOUT = ({"msg": "Request Timeout"}, 408)
CONFLICT = ({"msg": "Conflict"}, 409)
GONE = ({"msg": "Gone"}, 410)
LENGTH_REQUIRED = ({"msg": "Length Required"}, 411)
PRECONDITION_FAILED = ({"msg": "Precondition Failed"}, 412)
PAYLOAD_TOO_LARGE = ({"msg": "Payload too large"}, 413)
URI_TOO_LONG = ({"msg": "URI Too Long"}, 414)
UNSUPPORTED_MEDIA_TYPE = ({"msg": "Unsupported Media Type"}, 415)
REQUESTED_RANGE_NOT_SATISFIABLE = ({"msg": "Requested range not satifiable"}, 416)
EXPECTATION_FAILED = ({"msg": "Exception Failed"}, 417)
I_AM_A_TEAPOT = ({"msg": "I'm a teapot"}, 418)
UNPROCESSABLE_ENTITY = ({"msg": "Unprocessable entity"}, 422)
LOCKED = ({"msg": "Locked"}, 423)
FAILED_DEPENDENCY = ({"msg": "Failed Dependency"}, 424)
UPGRADE_REQUIRED = ({"msg": "Upgrade Required"}, 426)
PRECONDITION_REQUIRED = ({"msg": "Precondition Required"}, 428)
TOO_MANY_REQUESTS = ({"msg": "Too Many Requests"}, 429)
REQUEST_HEADER_FIELDS_TOO_LARGE = ({"msg": "Request Header Fields Too Large"}, 431)
UNAVAILABLE_FOR_LEGAL_REASONS = ({"msg": "Unavailable For Legal Reasons"}, 451)

INTERNAL_SERVER_ERROR = ({"msg": "Internal Server Error"}, 500)
NOT_IMPLEMENTED = ({"msg": "Not Implemented"}, 501)
BAD_GATEWAY = ({"msg": "Bad Gateway"}, 502)
SERVICE_UNAVAILABLE = ({"msg": "Service Unavailable"}, 503)
GATEWAY_TIMEOUT = ({"msg": "Gateway Timeout"}, 504)
HTTP_VERSION_NOT_SUPPORTED = ({"msg": "HTTP Version Not Supported"}, 505)
VARIANT_ALSO_NEGOTIATES = ({"msg": "Variant Also Negotiates"}, 506)
INSUFFICIENT_STORAGE = ({"msg": "Insufficient Storage"}, 507)
LOOP_DETECTED = ({"msg": "Loop Detected"}, 508)
BANDWIDTH_LIMIT_EXCEEDED = ({"msg": "Bandwidth Limit Exceeded"}, 509)
NOT_EXTENDED = ({"msg": "Not Extended"}, 510)
NETWORK_AUTHENTICATION_REQUIRED = ({"msg": "Network Authentication Required"}, 511)
