# Paste in https://editor.swagger.io/ to see what it looks like
openapi: 3.0.3
info:
  title: ECE_461L - OpenAPI
  description: |-
    This is the rough specifications for what our API will be doing
  version: 1.0.01
externalDocs:
  description: Google Drive Link
  url: https://drive.google.com/drive/u/2/folders/1R8sgbDksbZiwOycuF396ZUm8Dv0tAQy7
servers:
  - url: our_server_here.com
tags:
  - name: Projects
  - name: Users
    description: Operations about Users
  - name: Resources
    description: Operations about resources
paths:
  /users/profile:
    get:
      tags:
        - User
      summary: Find user by JWT
      description: Returns a single user
      operationId: getUserById
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
        '404':
          description: User not found
        '401':
          description: Unauthorized. JWT Token is missing or invalid
      security:
        - JWTAuth: []
    put:
      tags:
        - Users
      summary: Update 
      description: Update an user by JWT Token
      operationId: updateUser
      requestBody:
        description: Update an existent User
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'          
        '404':
          description: User not found
        '401':
          description: Unauthorized. JWT Token is missing or invalid
      security:
        - JWTAuth: []
  /users:  
    post:
      tags:
        - Users
      summary: Add a new user
      description: Add a user
      operationId: addUser
      requestBody:
        description: Create a new user
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/User'
        required: true
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'          
        '400':
          description: Invalid input
        '401':
          description: Unauthorized. JWT Token is missing or invalid
  /users/login:
    post:
      tags:
        - Users
      summary: Returns true if login correct with JWT corresponding
      description: Logs user in
      operationId: login
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'          
        '401':
          description: Unauthorized. JWT Token is missing or invalid
      security:
        - JWTAuth: []
  /users/logout:
    post:
      tags:
        - Users
      summary: Returns true if logout correct with JWT corresponding
      description: Logs user out
      operationId: logout
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/User'          
        '401':
          description: Unauthorized. JWT Token is missing or invalid
      security:
        - JWTAuth: []
  /projects:
    get:
      tags:
        - Projects
      summary: Poject list
      description: receive a list of projects of the user.
      security:
        - JWTAuth: []
      responses:
        '200':
          description: Access granted. Returns secure data.
          content:
            application/json:
              example:
                - id: 2
                  title: Project 1
                  description: This is for project 1
                  users:
                    - Mimi
                    - Frank
                    - Ayan
                  creator: Mimi
                  resources:
                    "Title 1": 3 # title -> usage
                    "Title 2": 2
                - id: 4
                  title: Project 2
                  description: This is for project 2
                  users:
                    - Frank
                    - Ayan
                  creator: Ayan
                  resources:
                    "Title 1": 3 # title -> usage
                    "Title 2": 2
        '401':
          description: Unauthorized. JWT token is missing or invalid.
          content:
            application/json:
              example:
                msg: User not found
    post:
      summary: Create a new project for a user
      security:
        - JWTAuth: []
      tags: 
        - Projects
      requestBody:
        description: Project data
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Project title
                description:
                  type: string
                  description: Project description
    
      responses:
        '200':
          description: Project created successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  projectId:
                    type: integer
                    description: ID of the created project
        '401':
          description: Unauthorized. JWT token is missing or invalid.
          content:
            application/json:
              example:
                msg: User not found
        '500':
          description: Internal server error. Failed to create the project.
          content:
            application/json:
              example:
                msg: error message
  /projects/{project_title}/users:
    post:
      summary: "Add a new user to the project"
      description: "Add a new user to the specified project."
      tags:
        - Projects
      security:
        - JWTAuth: []
      parameters:
        - name: "project_title"
          in: "path"
          description: "Name of the project to which the user will be added"
          required: true
          schema:
            type: "string"
          example: "Project 1"
      # requestBody:
      #   required: false
      #   content:
      #     application/json:
      #       schema:
      #         type: "object"
      #         properties:
      #           userId:
      #             type: "string"
      #             description: "Name of the user to be added to the project"
      #             example: "Mimi" # not required, if not provided, add yourself
              
      responses:
        '200':
          description: "User added to the project successfully"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  msg:
                    type: "string"
                    example: "User added to the project successfully"
        '401':
          description: Unauthorized. JWT token is missing or invalid.
          content:
            application/json:
              example:
                msg: User not found
       
        '500':
          description: "Internal Server Error: Failed to add user to the project"
          content:
            application/json:
              schema:
                type: "object"
                properties:
                  msg:
                    type: "string"
                    example: "error message"
  /resources:
    get:
      tags:
        - Resources
      summary: Resource list of all users
      description: receive a list of resources.
      security:
        - JWTAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resource'
        '401':
          description: Unauthorized. JWT token is missing or invalid.
  /resources/{resource_id}/checkin:
    post:
      tags:
        - Resources
      summary: Checks in specified amount of resource
      parameters:
        - name: resource_id
          in: path
          description: ID of resource to checkin
          required: true
          schema:
            type: integer
            format: int64
        - name: amount
          in: query
          description: amount of resources to checkin
          required: true
          schema:
            type: integer
      description: check specified amount of resources in
      security:
        - JWTAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resource'
        '400':
          description: Invalid request, tried to check in too many or illegal value
        '401':
          description: Unauthorized. JWT token is missing or invalid.
        '404': 
          description: Resource not found
  /resources/{resource_id}/checkout:
    post:
      tags:
        - Resources
      summary: Checks out specified amount of resource
      parameters:
        - name: resource_id
          in: path
          description: ID of resource to checkout
          required: true
          schema:
            type: integer
            format: int64
        - name: amount
          in: query
          description: amount of resources to checkout
          required: true
          schema:
            type: integer
      description: check specified amount of resources out
      security:
        - JWTAuth: []
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Resource'
        '400':
          description: Invalid request, tried to check out too many or illegal value
        '401':
          description: Unauthorized. JWT token is missing or invalid.
        '404': 
          description: Resource not found
components:
  schemas:
    Resource:
      required:
        - id
      properties:
        id:
          type: integer
          format: int64
          example: 10
        capacity:
          type: integer
          example: 100
        availability:
          type: integer
          example: 30
        title:
          type: string
        type:
          type: string
          enum:
            - type1
            - type2
        created_at:
          type: string
          format: date-time
          example: "2017-07-21T17:32:28Z" # https://datatracker.ietf.org/doc/html/rfc3339#section-5.6
    Projects:
      required:
        - id
        - title
      properties:
        id:
          type: integer
          format: int64
          example: 10
        title:
          type: string
          example: Project 1
        description:
          type: string
        user_ids:
          type: array
          example: [1, 2, 3]
        creator:
          type: integer
          description: User id of Creator
          format: int64
          example: 10
        resources:
          type: array
          description: array of resource ids
          example: [1, 3, 8]
    User:
      required:
        - name
        - id
      type: object
      properties:
        id:
          type: integer
          format: int64
          example: 10
        username:
          type: string
          example: spenc
        password:
          type: string
        created_at:
          type: string
          format: date-time
          example: "2017-07-21T17:32:28Z" # https://datatracker.ietf.org/doc/html/rfc3339#section-5.6
        project_ids:
          type: array
          items:
            $ref: '#/components/schemas/Projects'
  requestBodies:
    User:
      description: User object
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/User'
  securitySchemes:
    JWTAuth:
      type: apiKey
      in: cookie
      name: JWT