openapi: 3.0.0
info:
  version: 1.0.0
  title: Hardware as a Service (HaaS) System API
  description: API documentation for the Hardware as a Service (HaaS) system PoC
components:
  securitySchemes:
    JWTAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
paths:
  /projects/:
    get:
      summary: Poject list
      description: receive a list of projects of the user.
      security:
        - JWTAuth: []
      responses:
        '200':
          description: Access granted. Returns secure data.
          content:
            application/json:
              example:
               -  id: 2
                  title: "Project 1"
                  description: "This is for project 1"
                  users: ["Mimi", "Frank", "Ayan"]
                  creator: "Mimi"
                  resources list: [1, 3, 8]
               -  id: 8
                  title: "Project 2"
                  description: "This is for project 2"
                  users: ["Mimi", "Frank", "Ayan"]
                  creator: "Frank"
                  resources list: [2, 3, 8]
               
                
        '401':
          description: Unauthorized. JWT token is missing or invalid.
